name: Update ReadMe Stats

on:
  schedule:
    - cron: '0 * * * *' # This will run every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Update README
        uses: anuraghazra/github-readme-stats@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
