name: Update GitHub Stats

on:
  push:
    branches:
      - master  # Trigger on push to main branch
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write  # Allow the action to push changes

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with GitHub Stats
        run: |
          echo "![Your GitHub Stats](https://github-readme-stats.vercel.app/api?username=AsjadButt&show_icons=true&hide_title=true)" >> README.md
          echo "![Top Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=AsjadButt&layout=compact)" >> README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README with latest stats" || echo "No changes to commit"
          git push origin master  # Make sure this is your correct branch name
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Use your PAT here
